import Header from './components/Header';
import './globals.css';

export const metadata = {
  title: 'Floradex',
  // TODO add metadata
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex h-[100svh] flex-col'>
        <header className='flex h-[6rem]'>
          <Header />
        </header>
        <div className='content-container relative flex min-h-[calc(100svh-6rem)] flex-grow flex-col'>
          {children}
        </div>
      </body>
    </html>
  );
}
